import { DashboardStats, Competition, ContentItem, UserProfile, Transaction, SponsorAnalytics } from './types';

export const mockUser = {
  id: '1',
  name: 'Admin User',
  email: 'admin@gullyfame.com',
  role: 'admin' as const,
};

export const mockSponsorUser = {
  id: '2',
  name: 'Sponsor User',
  email: 'sponsor@gullyfame.com',
  role: 'sponsor' as const,
};

export const mockDashboardStats: DashboardStats = {
  totalUsers: 125430,
  totalEntertainers: 8540,
  totalContests: 234,
  liveContests: 12,
  upcomingContests: 8,
  completedContests: 214,
  totalEarnings: 2450000,
  tipsSent: 45678,
  subscriptionsCount: 1234,
  activeSponsors: 45,
};

export const mockCompetitions: Competition[] = [
  {
    id: '1',
    title: 'Hip-Hop Championship 2024',
    description: 'Showcase your hip-hop skills and compete with the best dancers in the country. This is the ultimate platform to demonstrate your talent.',
    rules: '1. All participants must be 18 years or older\n2. Content must be original hip-hop dance\n3. Video duration: 2-5 minutes\n4. No offensive content allowed\n5. Participants can submit only one entry\n6. Judging based on technique, creativity, and audience engagement',
    status: 'live',
    startDate: '2024-01-15',
    endDate: '2024-02-15',
    prizeAmount: 100000,
    category: 'Dance',
    winnerSlots: 3,
    bannerImage: 'https://via.placeholder.com/800x300',
    sponsorId: 'sp1',
    sponsorName: 'Brand X',
    sponsorLogo: 'https://via.placeholder.com/200x100',
    participants: 500,
    entries: 1250,
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    title: 'Dance Battle Delhi',
    description: 'Ultimate dance competition for all dance styles. Show your moves and win amazing prizes.',
    rules: '1. Open to all dance styles\n2. Age limit: 16+ years\n3. Video must be 3-7 minutes\n4. Original choreography required\n5. Multiple entries allowed (max 3)\n6. Winner selected by judges and public voting',
    status: 'upcoming',
    startDate: '2024-02-20',
    endDate: '2024-03-20',
    prizeAmount: 75000,
    category: 'Dance',
    winnerSlots: 5,
    bannerImage: 'https://via.placeholder.com/800x300',
    sponsorId: 'sp2',
    sponsorName: 'Brand Y',
    sponsorLogo: 'https://via.placeholder.com/200x100',
    participants: 0,
    entries: 0,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    title: 'Cooking Wars',
    description: 'Master chef competition for home cooks and professional chefs. Create amazing dishes and win cash prizes.',
    rules: '1. Must be 18+ years old\n2. Recipe must be original or credited\n3. Video duration: 5-15 minutes\n4. Show cooking process clearly\n5. One entry per participant\n6. Judged on taste, presentation, and creativity',
    status: 'completed',
    startDate: '2023-12-01',
    endDate: '2023-12-31',
    prizeAmount: 50000,
    category: 'Cooking',
    winnerSlots: 3,
    bannerImage: 'https://via.placeholder.com/800x300',
    sponsorId: 'sp1',
    sponsorName: 'Brand X',
    sponsorLogo: 'https://via.placeholder.com/200x100',
    participants: 234,
    entries: 567,
    createdAt: '2023-11-15',
  },
];

export const mockContentItems: ContentItem[] = [
  {
    id: '1',
    type: 'reel',
    title: 'Amazing Dance Performance',
    userId: 'u1',
    userName: 'Dancer Pro',
    status: 'pending',
    reports: 0,
    views: 1250,
    likes: 89,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    type: 'video',
    title: 'Cooking Tutorial',
    userId: 'u2',
    userName: 'Chef Master',
    status: 'reported',
    reports: 3,
    views: 3450,
    likes: 234,
    createdAt: '2024-01-14',
  },
  {
    id: '3',
    type: 'reel',
    title: 'Music Performance',
    userId: 'u3',
    userName: 'Music Star',
    status: 'approved',
    reports: 0,
    views: 5670,
    likes: 456,
    createdAt: '2024-01-13',
  },
];

export const mockUsers: UserProfile[] = [
  {
    id: 'u1',
    name: 'John Doe',
    email: 'john@example.com',
    phone: '+1234567890',
    role: 'entertainer',
    status: 'active',
    kycStatus: 'approved',
    joinDate: '2023-06-15',
    totalEarnings: 12500,
    totalTips: 8900,
    followers: 12500,
    following: 450,
  },
  {
    id: 'u2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    phone: '+1234567891',
    role: 'fan',
    status: 'active',
    kycStatus: 'pending',
    joinDate: '2024-01-10',
    totalEarnings: 0,
    totalTips: 0,
    followers: 0,
    following: 120,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: 't1',
    type: 'tip',
    amount: 500,
    userId: 'u1',
    userName: 'John Doe',
    status: 'completed',
    createdAt: '2024-01-15T10:30:00Z',
  },
  {
    id: 't2',
    type: 'purchase',
    amount: 1000,
    userId: 'u2',
    userName: 'Jane Smith',
    status: 'completed',
    createdAt: '2024-01-14T15:20:00Z',
  },
  {
    id: 't3',
    type: 'payout',
    amount: 5000,
    userId: 'u1',
    userName: 'John Doe',
    status: 'pending',
    createdAt: '2024-01-13T09:15:00Z',
  },
];

export const mockSponsorAnalytics: SponsorAnalytics = {
  totalViews: 1250000,
  totalReach: 850000,
  totalEntries: 3450,
  totalEngagement: 125000,
  brandVisibility: 89.5,
  competitions: [
    {
      id: '1',
      title: 'Hip-Hop Championship 2024',
      views: 450000,
      reach: 320000,
      entries: 1250,
      engagement: 45000,
    },
    {
      id: '2',
      title: 'Dance Battle Delhi',
      views: 800000,
      reach: 530000,
      entries: 2200,
      engagement: 80000,
    },
  ],
};

